### PR TITLE
Allow numeric time zone offsets

### PR DESCRIPTION
**Pull request by mluppi**
Some time formats were defined with a trailing `Z` which only allowed times in UTC to be parsed for these formats. Replacing `Z` with `Z07:00` makes it possible to parse numeric time zone offsets as well. One example is `2021-07-08T10:55:00+01:00` which conforms to [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339) and contains a numeric time offset.

I extended `csv_test.go` with cases for all the changed layout definitions.

### CODE REVIEW

**Comment by mluppi** [comment]
@marcusolsson Do you already know when this PR could be merged?

**Comment by mluppi** [comment]
Hi @tolzhabayev, @leventebalogh and @yesoreyeram
This PR has been open since a long time. Do you already know when it could be merged?

**Comment by yesoreyeram** [comment]
@mluppi - Thank you for the PR. I will take a look next week. Sorry for the delay.

Happy New year.

**Comment by ajunior** [comment]
Any news about this?

**Review by yesoreyeram — APPROVED** [review]

**Pull request merged**
